package ru.gymbay.models.bond

import com.squareup.moshi.Json
import ru.gymbay.models.bond.Board

data class BondMarketInfo(
    @field:Json(name = "BOARDID")
    val boardId: Board? = null,
    @field:Json(name = "TRADEDATE")
    val tradeDate: String? = null,
    @field:Json(name = "SHORTNAME")
    val shortName: String? = null,
    @field:Json(name = "SECID")
    val secId: String? = null,
    @field:Json(name = "NUMTRADES")
    val numTrades: Long? = null,
    @field:Json(name = "VALUE")
    val value: Double? = null,
    @field:Json(name = "LOW")
    val low: Double? = null,
    @field:Json(name = "HIGH")
    val high: Double? = null,
    @field:Json(name = "CLOSE")
    val close: Double? = null,
    @field:Json(name = "LEGALCLOSEPRICE")
    val legalClosePrice: Double? = null,
    @field:Json(name = "ACCINT")
    val accInt: Double? = null,
    @field:Json(name = "WAPRICE")
    val wapRice: Double? = null,
    @field:Json(name = "YIELDCLOSE")
    val yieldClose: Double? = null,
    @field:Json(name = "OPEN")
    val open: Double? = null,
    @field:Json(name = "VOLUME")
    val volume: Long? = null,
    @field:Json(name = "MARKETPRICE2")
    val marketPrice2: Double? = null,
    @field:Json(name = "MARKETPRICE3")
    val marketPrice3: Double? = null,
    @field:Json(name = "ADMITTEDQUOTE")
    val admittedQuote: Double? = null,
    @field:Json(name = "MP2VALTRD")
    val mp2ValTrd: Double? = null,
    @field:Json(name = "MARKETPRICE3TRADESVALUE")
    val marketPrice3TradesValue: Double? = null,
    @field:Json(name = "ADMITTEDVALUE")
    val admittedValue: Double? = null,
    @field:Json(name = "MATDATE")
    val matDate: String? = null,
    @field:Json(name = "DURATION")
    val duration: Long? = null,
    @field:Json(name = "YIELDATWAP")
    val yieldAtWap: Double? = null,
    @field:Json(name = "IRICPICLOSE")
    val iricpiClose: Any? = null,
    @field:Json(name = "BEICLOSE")
    val beiClose: Any? = null,
    @field:Json(name = "COUPONPERCENT")
    val couponPercent: Double? = null,
    @field:Json(name = "COUPONVALUE")
    val couponValue: Double? = null,
    @field:Json(name = "BUYBACKDATE")
    val buyBackDate: String? = null,
    @field:Json(name = "LASTTRADEDATE")
    val lastTradeDate: String? = null,
    @field:Json(name = "FACEVALUE")
    val faceValue: Long? = null,
    @field:Json(name = "CURRENCYID")
    val currencyId: String? = null,
    @field:Json(name = "CBRCLOSE")
    val cbrClose: Any? = null,
    @field:Json(name = "YIELDTOOFFER")
    val yieldToOffer: Double? = null,
    @field:Json(name = "YIELDLASTCOUPON")
    val yieldLastCoupon: Any? = null,
    @field:Json(name = "OFFERDATE")
    val offerDate: String? = null,
    @field:Json(name = "FACEUNIT")
    val faceUnit: String? = null,
    @field:Json(name = "TRADINGSESSION")
    val tradingSession: Long? = null
)